(()=>{'use strict';
const W=window.FizikceWorld3D,M=window.FizikceConcepts,c=window.FIZIKCE_SAMPLE,root=document.querySelector('#experiment');let value=6,explored=false;
const fmt=n=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:1}).format(n),esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function draw(){const m=M.model('ohm',{value});W.update(root.querySelector('.trial-scene'),W.markup('ohm',{voltage:value,power:m.power},'pilot-ohm',`${value} volt, ${fmt(m.current)} amper; direnç 6 ohm`).replace('alttaki deney kontrolleriyle','üstteki gerilim düğmeleriyle'));root.querySelectorAll('[data-trial-voltage]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.trialVoltage)===value));document.querySelector('#trial-result').textContent=`${value} V ÷ 6 Ω = ${fmt(m.current)} A · Güç: ${fmt(m.power)} W`;document.querySelector('#trial-feedback').textContent=value===9?'Ara basamak! Akım 1,5 A, güç 13,5 W. Tel daha kırmızı. Şimdi 12 V ile karşılaştır.':value===12?'Kıpkırmızı! 6 V’a göre akım 2 katına, güç 4 katına çıktı. Direnç yine 6 Ω. Renk, gücü temsil ediyor.':explored?'Yeniden 6 V: akım 1 A, güç 6 W. Kızarma azaldı; direnç hâlâ 6 Ω.':'Önce tahmin et: Gerilim artınca ne olur? Önce 9 V’a, sonra 12 V’a dokun.';document.querySelector('#trial-next').hidden=!explored;document.querySelector('#trial-step').textContent=explored?'1 ✓ Deneyi yaptın · 2 Kartı aç':'1 Deneyi değiştir · 2 Kartı aç';}
root.addEventListener('click',e=>{const b=e.target.closest('[data-trial-voltage]');if(!b)return;value=Number(b.dataset.trialVoltage);if(value>6)explored=true;draw();});
const card=document.querySelector('#sample-card');
card.innerHTML=`<p class="eyebrow">02 · AÇIKLAMA KARTI / ${c.grade}. SINIF · ${esc(c.topic)}</p><h2 id="sample-title" tabindex="-1">“${esc(c.phrase)}”</h2><div class="translation-box"><span class="section-label">Türkçesi şu</span><p>${esc(c.plain_meaning)}</p></div><div class="first-step"><span class="step-number">1</span><div><span class="section-label">İlk adımın</span><p>${esc(c.first_action)}</p></div></div><div class="trap-box"><span class="section-label">Küçük tuzağa dikkat</span><p>${esc(c.applicability_note)}</p></div><div class="pilot-question"><p class="eyebrow">03 · ŞİMDİ SIRA SENDE</p><h3>${esc(c.quiz.question)}</h3><div class="pilot-options" role="group" aria-label="Mini soru seçenekleri">${c.quiz.options.map((o,i)=>`<button class="quiz-option" type="button" data-answer="${i}" aria-pressed="false"><span>${'ABCDE'[i]}</span>${esc(o)}</button>`).join('')}</div><div id="answer-feedback" class="pilot-answer" role="status" aria-live="polite"></div><button class="secondary-button" type="button" id="retry" hidden>Tekrar dene ↻</button></div><details class="source-details"><summary>Kartın kitap ve programdaki yeri</summary>${c.sources.map(s=>`<p>MEB Fizik ${c.grade} · s. ${s.printed_page} · <a href="${esc(s.url)}#page=${s.pdf_page}" target="_blank" rel="noopener noreferrer">Kitap sayfasını aç ↗</a></p>`).join('')}<p>Açıklama ve mini soru özgündür. Öğrenme çıktısı: ${esc(c.outcome_codes.join(', '))}.</p></details>`;
document.querySelector('#open-sample').addEventListener('click',()=>{card.hidden=false;document.querySelector('#sample-title').focus({preventScroll:true});card.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});});
card.addEventListener('click',e=>{const b=e.target.closest('[data-answer]');if(b){const n=Number(b.dataset.answer);card.querySelectorAll('[data-answer]').forEach(el=>{el.disabled=true;el.setAttribute('aria-pressed',el===b);el.classList.toggle('answer-correct',Number(el.dataset.answer)===c.quiz.answer);el.classList.toggle('answer-wrong',el===b&&n!==c.quiz.answer);});document.querySelector('#answer-feedback').textContent=(n===c.quiz.answer?'Doğru! ':'Bir ayrıntı kaçtı. ')+c.quiz.feedback[n];document.querySelector('#retry').hidden=false;}if(e.target.closest('#retry')){card.querySelectorAll('[data-answer]').forEach(el=>{el.disabled=false;el.setAttribute('aria-pressed','false');el.classList.remove('answer-correct','answer-wrong');});document.querySelector('#answer-feedback').textContent='';document.querySelector('#retry').hidden=true;card.querySelector('[data-answer]').focus();}});
draw();
})();
