(()=>{'use strict';
const notes=[
{grade:9,topic:'Akışkanlar',phrase:'Serbestçe yüzüyor ve dengede',meaning:'Başka bir düşey kuvvet yoksa kaldırma kuvveti ağırlığa eşittir.',first:'Yukarı yönlü kaldırma kuvvetini ve aşağı yönlü ağırlığı çiz.',trap:'Denge, kuvvetlerin tek tek sıfır olması değildir. El, ip veya taban teması varsa ek kuvvetleri de hesaba kat.',formula:'Fₖ = G',example:'Ağırlığı 6 N olan cisim serbestçe ve dengede yüzüyorsa kaldırma kuvveti 6 N’dur. Daha yoğun sıvıda yine dengede yüzerse kuvvet 6 N kalır; batan hacim azalır.',check:'Daha yoğun sıvıya geçince aynı cismin kaldırma kuvveti mutlaka artar mı?',answer:'Hayır. Cisim yine serbestçe dengede yüzüyorsa Fₖ = G. Değişen, denge için gereken batan hacimdir.',symbol:'↑ Fₖ\n▰\n↓ G'},
{grade:10,topic:'Kuvvet ve Hareket',phrase:'İvmesi negatif',meaning:'İvme, seçilen negatif yöndedir. Hareketin yönünü ise o andaki hızın işareti gösterir.',first:'Hız ile ivmenin işaretlerini birlikte kontrol et: aynı işaret sürat artışı, zıt işaret sürat azalışı.',trap:'Negatif ivme her zaman yavaşlama değildir. “Hız” ile hızın büyüklüğü olan “sürat”i ayır.',formula:'v = v₀ + at',example:'Sağ yön pozitif: v₀ = −2 m/s, a = −1 m/s². İki saniye sonra v = −2 + (−1) × 2 = −4 m/s. Sürat 2’den 4 m/s’ye çıkar.',check:'v < 0 ve a < 0 ise araç yavaşlar mı?',answer:'Hayır. Hız ve ivme aynı yönde: araç sola doğru giderken sürati artar.',symbol:'← v\n🚙\n← a'},
{grade:11,topic:'Kuvvet ve Hareket',phrase:'Düşey harekette en yüksek noktada',meaning:'Düşey yukarı fırlatılan cismin hızı, tepe noktasında bir an için sıfırdır.',first:'Hız ve ivme için ayrı değerler yaz. Hava direnci yok ve yalnızca yer çekimi etkiliyse ivme aşağı yönlü g’dir.',trap:'Hızın sıfır olması ivmenin sıfır olması demek değildir. Eğik atışta tepe noktasında yalnız düşey hız bileşeni sıfır olur.',formula:'v = 0 · a = −g',example:'Yukarı yönü pozitif seç. Hava direnci yokken düşey atılan topun tepesinde v = 0, a = −10 m/s² (g = 10 m/s² alınır). Topun ağırlığı etkisini sürdürür.',check:'Top tepe noktasında bir an durduğuna göre net kuvvet de sıfır mı?',answer:'Hayır. Yalnızca yer çekimi varsa net kuvvet aşağı yönlü mg’dir. Hızın o andaki sıfır değeri bunu değiştirmez.',symbol:'v = 0\n●\n↓ g'}
];
const preview=document.querySelector('#note-preview');
function showNote(i){const n=notes[i];document.querySelectorAll('[data-note]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.note)===i));preview.innerHTML=`<div class="note-preview-top"><span>${n.grade}. SINIF · ${n.topic}</span><span>ÖRNEK ÇALIŞMA NOTU</span></div><h3>“${n.phrase}”</h3><div class="note-preview-grid"><div><span class="note-label">TÜRKÇESİ ŞU</span><p class="note-meaning">${n.meaning}</p><span class="note-label">İLK HAMLE</span><p>${n.first}</p></div><div class="note-diagram"><pre>${n.symbol}</pre><strong>${n.formula}</strong><small>Yönler ve gösterim temsilidir.</small></div></div><div class="note-warning"><strong>Tuzağı fark et</strong><p>${n.trap}</p></div><div class="note-example"><span class="note-label">KÜÇÜK BİR ÖRNEK</span><p>${n.example}</p></div><details class="note-check"><summary>${n.check}<span>Cevabı aç +</span></summary><p>${n.answer}</p></details>`;}
document.querySelectorAll('[data-note]').forEach(b=>b.addEventListener('click',()=>showNote(Number(b.dataset.note))));showNote(0);
const steps=[
['01 / İFADEYİ YAKALA','“Serbestçe yüzüyor<br>ve dengede.”','Sorudaki koşulu bul. “Serbestçe” ve “dengede” sözcükleri hangi kuvvetleri karşılaştıracağını söylüyor.','<span class="tour-chip">SERBESTÇE</span><span class="tour-chip">DENGEDE</span>'],
['02 / NOTU ANLA','Yukarı iten kuvvet.<br>Aşağı çeken ağırlık.','Başka düşey kuvvet yoksa bu iki kuvvetin büyüklükleri eşit. İlk hamlen, kuvvetleri çizmek.','<span class="tour-formula">↑ Fₖ = G ↓</span>'],
['03 / TUZAĞI FARK ET','Dengede olmak,<br>kuvvetsiz olmak değil.','Net kuvvet sıfırdır. Kaldırma kuvveti ve ağırlık ayrı ayrı sıfır olmak zorunda değildir.','<span class="tour-chip">NET KUVVET = 0</span><span class="tour-chip">KUVVETLER VAR</span>'],
['04 / SORUDA KULLAN','Ağırlık 6 N ise<br>kaldırma kuvveti kaç N?','Serbestçe ve dengede yüzme koşulunda Fₖ = G = 6 N. Formülü seçmeden önce koşulu anladın.','<span class="tour-formula">6 N ✓</span>']
];
let step=0,timer=null;const play=document.querySelector('#tour-play'),stage=document.querySelector('#tour-stage');
function render(){const s=steps[step];stage.innerHTML=`<div class="tour-count">${s[0]}</div><h3>${s[1]}</h3><p>${s[2]}</p><div class="tour-visual">${s[3]}</div>`;document.querySelectorAll('[data-tour]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.tour)===step));}
function stop(){clearInterval(timer);timer=null;play.textContent='▶ Tanıtımı oynat';play.setAttribute('aria-pressed','false');stage.setAttribute('aria-live','polite');}
play.addEventListener('click',()=>{if(timer){stop();return;}if(step===3)step=0;stage.setAttribute('aria-live','off');render();play.textContent='Ⅱ Duraklat';play.setAttribute('aria-pressed','true');timer=setInterval(()=>{if(step===3){stop();return;}step++;render();},6500);});
document.querySelectorAll('[data-tour]').forEach(b=>b.addEventListener('click',()=>{stop();step=Number(b.dataset.tour);render();}));document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});render();
})();
